# Generated by Django 3.2.23 on 2024-12-01 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surface_type', models.IntegerField()),
                ('road_traffic', models.IntegerField()),
                ('road_name', models.CharField(max_length=255)),
                ('condition', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('risk_level', models.FloatField()),
                ('image_path', models.CharField(max_length=255)),
                ('bounding_box', models.JSONField()),
                ('updated_at', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
