# Generated by Django 3.2.23 on 2024-12-03 12:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('road_info', '0002_auto_20241201_0926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadinfo',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='roadinfo',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
