# Generated by Django 3.2.23 on 2024-12-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_info', '0003_auto_20241203_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roadinfo',
            old_name='road_traffic',
            new_name='bad_type',
        ),
        migrations.RenameField(
            model_name='roadinfo',
            old_name='surface_type',
            new_name='road_category',
        ),
        migrations.AddField(
            model_name='roadinfo',
            name='speed',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
