# Generated by Django 3.2.23 on 2024-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_info', '0004_auto_20241212_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadinfo',
            name='road_category',
            field=models.CharField(max_length=255),
        ),
    ]
