# Generated by Django 3.2.23 on 2024-12-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_info', '0005_alter_roadinfo_road_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadinfo',
            name='bad_type',
            field=models.CharField(max_length=255),
        ),
    ]
