# Generated by Django 3.2.23 on 2024-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_info', '0006_alter_roadinfo_bad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadinfo',
            name='bad_type',
            field=models.IntegerField(),
        ),
    ]
