# Generated by Django 3.2.23 on 2024-12-14 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('road_info', '0007_alter_roadinfo_bad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadinfo',
            name='bounding_box',
        ),
    ]
